### ISSUE TITLE
License problem with included SFconv/ConvertUTF.[ch] files

### ISSUE THREAD

**Issue by juliangilbey** [silnrsi/teckit#1]
Hello!

Thanks for your really helpful TECkit package!

The license conditions say that the package is licensed under the CPL or the GNU LGPL.  However, Debian has recently noticed that the included ConvertUTF.c and ConvertUTF.h files from Unicode, Inc. have different license conditions, ones which Debian has decided do not fulfil the Debian Free Software Guidelines.  See [Debian bug #823100](http://bugs.debian.org/823100) for a discussion of this.  It turns out that this code is embedded within TeX Live too, as TECkit is used by XeTeX!  And it is also embedded in a variety of other pieces of software, too.

Would it be feasible to either ask Unicode, Inc. to relicense this code, or to write replacement code which is licensed under the conditions of the rest of this package?

With many thanks!

P.S. This issue is now also being tracked in Debian for the experimental TECkit package at [Bug #850438](http://bugs.debian.org/850438).

**Comment by neilmayhew** [comment]
Some background info that may be useful:

The use of `ConvertUTF.[ch]` is confined to calling a single function in a single place in the TECkit source code. The function is `ConvertUTF8toUTF16` and it's used in `SFconv/SFconv.cpp`, which is used to build the `sfconv` binary.

This binary isn't used by TeX Live or any other package that integrates TECkit. So one solution would be to move `SFConv` to a separate source repo.

Another alternative would be to use ICU, and the closest equivalent ICU function appears to be `u_strFromUTF8Lenient`. The extra dependency could be a hassle, so it might still be helpful to move `SFConv` to a separate project.

**Comment by juliangilbey** [comment]
That's really interesting, Neil, thank you!  Moving it out seems a fine solution.  Alternatively, I wonder whether it would be relatively easy to either just write a replacement for this one single function, or to bundle the requisite part of the ICU code (which has a clean license, in DFSG terms) in place of ConvertUTF.[ch]?

Best wishes, and thanks for the speedy and super-helpful response.

Julian

**Comment by neilmayhew** [comment]
@juliangilbey, I looked at the code of `u_strFromUTF8Lenient` in the ICU source and it's more than just a few lines, so It seems a pity to proliferate code unnecessarily by copying it. Also, it's important to do UTF conversion 'right' so I think it's better not to throw something together that may not handle the edge cases correctly when there's already tried and tested code available in existing libraries.

I'm not a maintainer of TECkit any more, but I think @devosb may be in a position to make the necessary changes.

**Comment by juliangilbey** [comment]
Actually, `u_strFromUTF8Lenient` assumes that the UTF8 string is well-formed.  I don't know whether you can make this assumption in SFConv; if not, then I assume that `u_strFromUTF8` would be preferable?

**Comment by neilmayhew** [comment]
Since the existing call to `ConvertUTF8toUTF16` specifies `lenientConversion` I assumed the lenient ICU function would be the closest equivalent. However, this could be reviewed by the person refactoring the code.

**Comment by devosb** [comment]
I agree with @neilmayhew about ICU dependency being a hassle. Maybe not on Debian, but I am not sure about Windows (for which the binaries are built on Linux) and macOS. @tim-eves has code to replace the non-free code and that work can be done next week.

**Comment by juliangilbey** [comment]
Awesome, thanks!

**Comment by jmallach** [comment]
Hello @tim-eves, @devosb and @juliangilbey! Is there any update on this? I'm facing the same problem on an unrelated project, and would be interested in looking at that replacement code.

**Comment by tim-eves** [comment]
I'm investigating 2 possible soultions with @devosb:
1) We have a mature and small UTF{8,16,32} decoder/encoder module from Graphite which could be used to replace this code. It's well tested and stable. That would let us avoid an ICU dependency, though we'd be cut and pasting code.
2) For the windows case we could statically link teckit to the ICU, that might require the icudt56.dll in addition to the teckit binary to be shipped for windows.

**Comment by neilmayhew** [comment]
@tim-eves Don't forget that this is needed only in `SFconv` which is very specific to SIL's needs, and it's possible that not even SIL is using it now.

**Comment by tim-eves** [comment]
Passes the (limited for sfconv) test suite provided and this decoder is slightly more lenient than the Unicode, Inc version when it comes to rejecting UTF8 encoded UTF16 surrogates but given the limited user base @devosb and I decided to accept that.
