### ISSUE TITLE
Remove README?

### ISSUE THREAD

**Issue by spl** [silnrsi/teckit#14]
During #13, I discovered that there is both a `README.md` file and a `README` file. I think it would be a good idea to remove one, probably the `README` since it is not nicely formatted by GitHub's markdown renderer. Consequently, the information in the `README` should be transferred either to the `README.md` and/or to `NEWS`. I think the information about changes would be most appropriate in `NEWS`.

**Comment by devosb** [comment]
While indeed the file `README` is not nicely formatted by GitHub, that was never the intent. The purpose of the file is to serve as documentation in both the Windows and Debian package of the Unicode version the TECkit compiler supports. In addition, it documents the runtime files needed by the Windows executables.

Having the runtime file information in `README.md` looks very nice, but is not (currently) in the Windows package (or the Debian package), plus Windows users may not have a program to format the markdown for them.

So the file could be renamed, you then need to get that file included in the tarball that is created for use with the Debian package. Doable, but there were other priorities. You can see some of that history of trying to rename the `README` file at commit https://github.com/silnrsi/teckit/commit/915558b61b97ead295656701febfd2f59cf96f1e
