### ISSUE TITLE
Remove Changelog?

### ISSUE THREAD

**Issue by spl** [silnrsi/teckit#15]
During #13, I discovered that there is both a `ChangeLog` file (empty) and a `NEWS` file. Is the former left over from before `git`? Can it be removed?

**Comment by devosb** [comment]
The file `ChangeLog` is indeed before `git`, as the file mentions `subversion`. So at the very least, the file needs to be updated. The GNU Coding Standards at https://www.gnu.org/prep/standards/standards.html#NEWS-File mention both a NEWS file and a ChangeLog. Which is probably why the project has both files. I think I will update the `ChangeLog` file to mention git.
