### ISSUE TITLE
Fix Travis-CI for Windows

### ISSUE THREAD

**Issue by spl** [silnrsi/teckit#20]
Travis-CI is failing in the cross-compilation of Windows binaries. I believe the error is here:

```
make[2]: Entering directory '/home/travis/build/spl/teckit/windows-build32/lib'
  CXX      ../source/Compiler.lo
[...]
i686-w64-mingw32-windres   -o Compiler_ver.o ../../source/Compiler_ver.rc
  CXXLD    TECkit_Compiler_x86.la
/usr/bin/ld: unrecognized option '--add-stdcall-alias'
/usr/bin/ld: use the --help option for usage information
collect2: error: ld returned 1 exit status
Makefile:687: recipe for target 'TECkit_Compiler_x86.la' failed
[...]
The command "./build-windows-binaries.sh" exited with 2.
```

I looked into the `ld` error on Travis-CI:

```sh
$ /usr/bin/ld --version
GNU ld (GNU Binutils for Ubuntu) 2.26.1
```

```sh
$ /usr/bin/ld --help
Usage: /usr/bin/ld [options] file...
Options:
[...]
  --add-stdcall-alias                Export symbols with and without @nn
[...]
```

I'm not sure what the error means, since it appears that `ld` does have the `--add-stdcall-alias` flag.

But is this the right `ld` executable here? Or is there a different one from the MinGW packages that should be used?

In the process of looking into this, I found this warning from `../configure`:

```
configure: WARNING: using cross tools not prefixed with host triplet
```

Searching for the warning led me to a page in the `autoconf` manual on [Specifying target triplets](https://www.gnu.org/software/autoconf/manual/autoconf-2.65/html_node/Specifying-Target-Triplets.html). I wonder if that could be related to the `ld` error.

There are a number of posts around the internet with similar `ld` error reports, but the solution never seems to have anything to do with the `ld` flag `--add-stdcall-alias` itself. Plus, I'm assuming the TECkit developers use this script locally, so it must work in some places.

**Comment by devosb** [comment]
I think you are correct, Travis is not using the correct ld. Running the script locally on Ubuntu Bionic amd64 I get the same warning from `configure`, but the build works. The linkers `/usr/bin/i686-w64-mingw32-ld` and `/usr/bin/x86_64-w64-mingw32-ld` are found (on my local machine and Travis) so I don't know why the difference in result happens.

**Comment by spl** [comment]
That's helpful. I verified that Travis does indeed have `/usr/bin/i686-w64-mingw32-ld` and `/usr/bin/x86_64-w64-mingw32-ld`. But this snippet from `../configure` output is strange:

```
checking build system type... x86_64-pc-linux-gnu
checking host system type... i686-w64-mingw32
checking target system type... i686-w64-mingw32
[...]
checking whether we are cross compiling... yes
[...]
checking for i686-w64-mingw32-gcc... gcc
checking whether we are using the GNU C compiler... yes
[...]
checking for ld used by gcc... /usr/bin/ld
[...]
checking for ld used by g++... /usr/bin/ld
```

I would not expect `/usr/bin/ld` there.

**Comment by spl** [comment]
The problem was that ~~`make`~~ `configure` was not using the correct `gcc` and `g++`. Defining `CC` and `CXX` fixed that. I also fixed a few minor documentation generation issues after the build started working.

**Comment by spl** [comment]
I now think the `configure` warning was just about `mt` not being the mingw manifest tool:

```
checking for i686-w64-mingw32-mt... no
checking for mt... mt
configure: WARNING: using cross tools not prefixed with host triplet
checking if mt is a manifest tool... no
```

I don't know what `mt` is or if it's being used.

**Comment by devosb** [comment]
`mt` is for working with magnetic tape drives, not something we need for TECkit! The man page for `mt` states this description, as well as `mt` being attached to the `cpio` command. It makes sense that `configure` would have a check to make sure the `mt` being used was for manifests, not tapes.
