### ISSUE TITLE
installed teckit from 18.04 crashes

### ISSUE THREAD

**Issue by mhosken** [silnrsi/teckit#25]
The attached text file and .tec seg faults txtconv.
[Big_mouth_frog_story-kali.txt](https://github.com/silnrsi/teckit/files/3508063/Big_mouth_frog_story-kali.txt)
[kali-mymr.zip](https://github.com/silnrsi/teckit/files/3508067/kali-mymr.zip)

**Comment by tim-eves** [comment]
Discovered to be a corrupted tec file recompiling the source file fixed the issue
