### ISSUE TITLE
syntax error near unexpected token `config.h'

### ISSUE THREAD

**Issue by elisebell** [silnrsi/teckit#28]
I get an error when attempting to run ./configure from a new download of TECkit 2.5.10 (from https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=TECkitDownloads) on MacOS Mojave version 10.14.5 

./configure: line 2118: syntax error near unexpected token `config.h'
./configure: line 2118: `AM_CONFIG_HEADER(config.h)'

Any help would be appreciated, please let me know if I should provide any additional information.

**Comment by devosb** [comment]
I was not able to reproduce the error. The configure file I have (generated on Ubuntu Bionic and Focal) have different content on line 2118. Did you run `sh autogen.sh`? Did you run `./build-mac-binaries.sh`? What version of _Xcode_ are you using?

There is a pre-compiled package for macOS on the download page, does that work for you?

**Comment by elisebell** [comment]
I first tried to run autogen.sh after cloning the teckit repository and received an error:

> *** Recreating libtool files
> glibtoolize: putting auxiliary files in '.'.
> glibtoolize: copying file './ltmain.sh'
> glibtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
> glibtoolize: copying file 'm4/libtool.m4'
> glibtoolize: copying file 'm4/ltoptions.m4'
> glibtoolize: copying file 'm4/ltsugar.m4'
> glibtoolize: copying file 'm4/ltversion.m4'
> glibtoolize: copying file 'm4/lt~obsolete.m4'
> *** Recreating aclocal.m4
> aclocal
> ./autogen.sh: line 30: aclocal: command not found
> *** Recreating configure
> autoheader: error: AC_CONFIG_HEADERS not found in configure.ac
> configure.ac:3: error: possibly undefined macro: AM_CONFIG_HEADER
>       If this token and others are legitimate, please use m4_pattern_allow.
>       See the Autoconf documentation.
> configure.ac:8: error: possibly undefined macro: AM_INIT_AUTOMAKE
> configure.ac:10: error: possibly undefined macro: AM_MAINTAINER_MODE
> configure.ac:11: error: possibly undefined macro: AM_SILENT_RULES
> configure.ac:16: error: possibly undefined macro: AM_PROG_CC_C_O
> configure.ac:18: error: possibly undefined macro: AC_PROG_LIBTOOL
> configure.ac:33: error: possibly undefined macro: AM_CONDITIONAL
> *** Recreating the Makefile.in files
> ./autogen.sh: line 40: automake: command not found

When I run build-mac-binaries, this is the output:

> ./build-mac-binaries.sh 
> 
> # This is how the Mac binaries for release are built, so I don't forget!
> # Any existing mac-build and teckit-mac/{bin,lib} directories will be deleted.
> # then go to mac-installer/ and run ./create-pkg.sh to generate the pkg and dmg.
> 
> rm -rf mac-build teckit-mac
> 
> mkdir mac-build
> cd mac-build
> 
> ../configure --enable-final --disable-dependency-tracking
> configure: WARNING: unrecognized options: --disable-dependency-tracking
> ../configure: line 2118: syntax error near unexpected token `config.h'
> ../configure: line 2118: `AM_CONFIG_HEADER(config.h)'

The config.log file in the mac-build directory after attempting to run build-mac-binaries:
[config.log](https://github.com/silnrsi/teckit/files/5284727/config.log)

When I download and install the pre-compiled package for macOS from the download page, the install seems to proceed correctly, but I have not been able to locate the installation after, which is incredibly frustrating. Thanks for your time, I appreciate it.

**Comment by devosb** [comment]
It looks like `automake` is missing. I think you need to install the whole _autoconf_ package, which should include `automake`. I suspect that Homebrew (or maybe MacPorts) could be used to install _autoconf_ on macOS. I don't have macOS, so I have only heard of these projects, not used them myself.

@n7s produced the macOS package, so he might know where the binaries are installed.

**Comment by elisebell** [comment]
_automake_ is installed and up-to-date, and is in my PATH, so I don't understand why that error is recurring. Thanks for your help, I'm not going to mess around with this any more, so this issue can be closed.

**Comment by neilmayhew** [comment]
> When I download and install the pre-compiled package for macOS from the download page, the install seems to proceed correctly, but I have not been able to locate the installation after, which is incredibly frustrating.

For the record, the program files are installed into `/usr/local/bin` and this directory is in `PATH` so you should be able to run any of the programs by typing its name into a terminal. These programs are:

* `sfconv`
* `teckit_compile`
* `txtconv`

You can also view their documentation with `man`.

If you were looking for a GUI program in `Applications`, unfortunately this project doesn't provide one. As the README says, "TECkit is a low-level toolkit intended to be used by applications for conversions between text encodings". There used to be a 'droplet' utility that could be used to convert files by dropping them onto its icon, but I think that's been unmaintained for a long time. However, it would be easy to write an AppleScript wrapper that functions as a droplet. It would also be possible to use [DropScript](https://github.com/RJVB/DropScript) to produce something similar.

**Comment by neilmayhew** [comment]
The README also has links to more user-friendly tools that are built on top of the TECkit library.
