### ISSUE TITLE
Compilation issues with v2.5.3

### ISSUE THREAD

**Issue by pati-ni** [silnrsi/teckit#3]
Building the TECkit-2.5.3 package as part of the xetex build fails during compilation:
```
In file included from ../../../source/libs/teckit/TECkit-2.5.3/source/Engine.cpp:120:0:
../../../source/libs/teckit/TECkit-2.5.3/source/NormalizationData.c:2575:1: error: narrowing conversion of ‘69786’ from ‘int’ to ‘UInt16 {aka short unsigned int}’ inside { } [-Wnarrowing]
 };
 ^
../../../source/libs/teckit/TECkit-2.5.3/source/NormalizationData.c:2575:1: error: narrowing conversion of ‘69788’ from ‘int’ to ‘UInt16 {aka short unsigned int}’ inside { } [-Wnarrowing]
../../../source/libs/teckit/TECkit-2.5.3/source/NormalizationData.c:2575:1: error: narrowing conversion of ‘69803’ from ‘int’ to ‘UInt16 {aka short unsigned int}’ inside { } [-Wnarrowing]

```

I am using gcc 7.2.0

**Comment by neilmayhew** [comment]
IIRC this was fixed several years ago. Maybe you're not using the latest
sources?

**Comment by pati-ni** [comment]
Probably, xetex comes bundled with an TECkit install so this might be it. Do you know if there a patch available for that problem?

**Comment by neilmayhew** [comment]
If it's the same problem, it was fixed in ab0d77df28ca96274e47f44086db991a295d3c6a in 2014.

Version 2.5.3 is very old now. I believe 2.5.7 is the current one. We would much prefer that you update to the newer version than patch the old one.

**Comment by pati-ni** [comment]
Awesome, patching the latest version seems to do the trick with xetex. Thanks a lot.

**Comment by neilmayhew** [comment]
FYI, most people get XeTeX by installing TeX Live, which includes XeTeX, and is using TECkit 2.5.7. Is there any reason why you can't use TeX Live?

**Comment by pati-ni** [comment]
No not really, thanks for the tip!
