### ISSUE TITLE
Doesn't seem to work for characters in plane 1

### ISSUE THREAD

**Issue by toby-1-kenobi** [silnrsi/teckit#30]
I had a font with characters assigned to the PUA in plane 0 and later the script got accepted into the unicode standard and is now in plane 1. I made a teckit map (by hand) to do the converting, but couldn't get any success from it in Ubuntu. So I booted into Windows and install SIL Converters. When I opened the teckit editing program there I noticed that the font glyph preview windows only let you preview characters in plane 0. I copied the map I had made into the editor and tried to use it in the test area. It seemed to convert the original PUA characters to some other codepoints in plane 0, but not to the plane 1 codepoints specified in the map.

Here is the map I made:

```
EncodingName            "SIL-Hispa-2018"
DescriptiveName         "Hispa.ttf font makes use of the Private Use Space of unicode to represent the Toto characters. Now they have been accepted into Unicode proper."
Version                 "0"
Contact                 "mailto:andy_tee@sall.com"
RegistrationAuthority   "SIL International"
RegistrationName        "Hispa-2018"

RHSFlags		(ExpectsNFC)	;NFC means that when going from Unicode back to legacy, the incoming data will be NFC-normalized before the mapping rules are applied. You can't normalize the LHS legacy data.

;these lines should be included in all normal TECkit maps, for handling
;characters below 32.
ByteClass [CTL] = (   0x00 .. 0x1f   )
UniClass  [CTL] = ( U+0000 .. U+001f )
[CTL]	<>	[CTL]

pass(Unicode)

U+e600			<>	U+01e290			; 𞊐
U+e601			<>	U+01e291			; 𞊑
U+e602			<>	U+01e296			; 𞊖
U+e603			<>	U+01e292			; 𞊒
U+e604			<>	U+01e293			; 𞊓
U+e605			<>	U+01e297			; 𞊗
U+e606			<>	U+01e294			; 𞊔
U+e607			<>	U+01e295			; 𞊕
U+e608			<>	U+01e298			; 𞊘
U+e609			<>	U+01e299			; 𞊙
U+e60a			<>	U+01e29c			; 𞊜
U+e60b			<>	U+01e29f			; 𞊟
U+e60c			<>	U+01e29a			; 𞊚
U+e60d			<>	U+01e29d			; 𞊝
U+e60e			<>	U+01e2a0			; 𞊠
U+e60f			<>	U+01e29b			; 𞊛
U+e610			<>	U+01e29e			; 𞊞
U+e611			<>	U+01e2ae			; ◌𞊮
U+e612			<>	U+01e2a1			; 𞊡
U+e613			<>	U+01e2a2			; 𞊢
U+e614			<>	U+01e2a3			; 𞊣
U+e615			<>	U+01e2a5			; 𞊥
U+e616			<>	U+01e2a6			; 𞊦
U+e617			<>	U+01e2a7			; 𞊧
U+e618			<>	U+01e2a8			; 𞊨
U+e619			<>	U+01e2aa			; 𞊪
U+e61a			<>	U+01e2ab			; 𞊫
U+e61b			<>	U+01e2ac			; 𞊬
U+e61c			<>	U+01e2aa U+01e2ae	; 𞊪𞊮
U+e61d			<>	U+01e2ad			; 𞊭
U+e61e			<>	U+01e2ab U+01e29b	; 𞊫𞊛
U+e61f			<>	U+01e2a6 U+01e298	; 𞊦𞊘
U+e620			<>	U+01e2a9			; 𞊩
U+e622			<>	U+0027				; quotesingle
U+e623			<>	U+01e2a4			; 𞊤
U+e612 U+e621	<>	U+01e2a2			; 𞊢
U+e614 U+e621	<>	U+01e2a4			; 𞊤
U+e616 U+e621	<>	U+01e2a7			; 𞊧
U+e618 U+e621	<>	U+01e2a9			; 𞊩
U+e61a U+e621	<>	U+01e2ac			; 𞊬
```

**Comment by DavidLRowe** [comment]
Unfortunately (as you note) the editor has an upper limit of U+FFFF. This is a known limitation.

I made a map file with the line
`U+e600 <> U+01e290`
from your original. In the test area, I entered `e600` in the Left-side Sample field and typed Alt+X to convert it to the actual character. In the Right-side Sample field I get a square box since I don't have a font to display that character, but the character itself is U+1E290 TOTO LETTER PA. 

Below that are displayed two values: U+D838 U+DE90. These are a surrogate pair, which together are used to encode a value higher than U+FFFF. If you decode those you'll find they yield the character value U+1E290. So the map is producing the correct plane 1 character, and the editor is displaying it as best it can.

So I think your map file is correct. Are you having trouble using it to covert data? If so, can you provide more specifics and possibly an example?

**Comment by toby-1-kenobi** [comment]
OK, yes I also have it working now. It worked when I opened a fresh TECkit editor project and copied just the character mappings into the map file. However when I opened the whole map file that I had previously made directly into the editor then it didn't work. So probably I did something wrong in the file header directives.

Thanks for your help.

**Comment by DavidLRowe** [comment]
Glad you have it working. I'll close this issue. (Reopen it or open another if you have further problems.)

**Comment by devosb** [comment]
The mapping editor should now be able to handle codepoints above 0xFFFF, this was one of the changes made for [SIL Converters 5.0](https://github.com/silnrsi/silconverters/releases/tag/v5.0). Do you know what version you installed?

You mentioned copying just character mappings and the mapping editor worked. Did you copy the literal Toto characters that are comments in the mapping file as well? TECkit should be able to handle those (assuming you use UTF-8 or maybe UTF-16 with a BOM). I don't know about the mapping editor.

Personally, I use all ASCII for TECkit maps. If you need to document the conversion more than just what the codepoint gives you, you can use the character name. For example, the first line could be written as
```
U+e600 <> toto_letter_pa
```
